# Site settings
title: Drift Diary
footer_title: このブログについて
email: drikin@gmail.com
description: >
  このブログはドリキンのガジェット散財や気になる事全般を書き記す個人ブログです。
baseurl: ""
url: "http://blog.drikin.com"
author: ドリキン
twitter_username: drikin
github_username:  drikin

# Build settings
markdown: redcarpet
